admin:
    username: donald
    first_name: Donald
    last_name: Piret
    password: santaclaus
    email: donald@donaldpiret.com
    phone_number: "+32476941823"
    
info: |
    Christmas dinner on the 24th of December